Draft of on-sky setup documentation
magao-x/handbook pull request #16
Opened 2024-04-19 18:22 UTC by jlibermann

- Docs describing how to set up the AO system on-sky, prior to starting science observations

2024-04-22 16:14 UTC, joseph-long commented
Thanks for this, @jlibermann. It looks like something funky happened with [index.rst](https://github.com/magao-x/handbook/pull/16/files#diff-7a924611aedd6e8774071db56568b2d7bc208abd04e63b808c4f0f22d57663ae). It could be windows line endings. Could you correct that so the only edited lines are the one you actually added?

2024-08-04 19:35 UTC, jaredmales requested changes
Great job @jlibermann.  A few details to clean up.  I think we want to reorganize a little to add an alignment procedure, based on the one I put on slack and is pinned, as a separate thing that happens before acquisition and loop-closing.  You can get higher quality figures for the guis using your remote operations ability and screen-shotting them.

2024-08-04 19:35 UTC, jaredmales commented on operating/loop_gain_dist.png
please get a higher quality image

2024-08-04 19:35 UTC, jaredmales commented on operating/offloading_ctrl_gui.png
please get a higher quality image

2024-08-04 19:35 UTC, jaredmales commented on operating/cam_acq.png
please get a higher quality image when we are next on sky. It's good to show an real image so this one is good enough for now.

2024-08-04 19:35 UTC, jaredmales commented on operating/on_sky.rst
> +   * Set the FPS on the ``camwfsctrl`` GUI to ``2000``
it's not always 2000.  How about "desired frequency"

2024-08-04 19:35 UTC, jaredmales commented on operating/on_sky.rst
> +   * In CursesINDI, type ``fxngensync`` and toggle the state to ``On`` (see the `cursesINDI guide <./software/guis/cursesINDI>`__ if you need a refresher)
state of what?  it's C1outp

2024-08-04 19:35 UTC, jaredmales commented on operating/on_sky.rst
> +   * Click ``Rest`` and wait for the modulator to change to the ``resting`` state
this is not necessary. please remove

2024-08-04 19:35 UTC, jaredmales commented on operating/on_sky.rst
> +   * Under ``Frequency`` type ``2000`` and press the enter key.
it's not always 2000.

2024-08-04 19:35 UTC, jaredmales commented on operating/on_sky.rst
> +   * Under ``Radius`` type ``2.5`` and press the enter key.
it's not always 2.5

2024-08-04 19:35 UTC, jaredmales commented on operating/on_sky.rst
> +   * Click ``Set`` and again wait for the modulator status to update.
this is not generally necessary.  the modulator should have been set during initial alignment.

2024-08-04 19:35 UTC, jaredmales commented on operating/on_sky.rst
> +If this is the beginning of the night, start from Step 1. Otherwise, proceed to Step 2.
you need to discuss alignment or link/refer to the startup alignment procedure.  i.o.w. we should specify that the initial conditions are a fully powered on instrument aligned to the internal source.

2024-08-04 19:35 UTC, jaredmales commented on operating/on_sky.rst
> +2. Once the telescope operator tells you that they are pointing at the target, navigate to the telescope acquisition box on the MagAO-X web interface (https://exao1.magao-x.org/#/): |image2|
This is a step that should be one when we decide to go on sky.  It is not generally necessary for each target.  I think we want to have a separate section that is "switch from lab to on-sky operations", noting that you can just run the scripts xlabmode and xskymode to switch back and forth

2024-08-04 19:35 UTC, jaredmales commented on operating/on_sky.rst
> +   * move the acquisition mirror to the ``In`` position
this is step is part of per-star acquisition

2024-08-04 19:35 UTC, jaredmales commented on operating/on_sky.rst
> +   * Set ``K-mirror tracking``, ``ADC tracking``, and ``telescope T/T offload`` to ``On``.
not part of per-star acq

2024-08-04 19:35 UTC, jaredmales commented on operating/on_sky.rst
> +   * Press the ``acquire from guider`` button (it should light up red after putting in the acquisition mirror). You are now controlling the telescope.
this is part of per-star acq

2024-08-04 19:35 UTC, jaredmales commented on operating/on_sky.rst
> +3. If observing in Halpha:
this should be a separate section that is before acqusition starts.  you have to complete re-align the system so it should be done on the internal source in most cases.

2024-08-04 19:35 UTC, jaredmales commented on operating/on_sky.rst
> +   *  **IMPORTANT** Set ``EM gain`` on the ``camwfsctrl``, ``camsci1ctrl``, and ``camsci2ctrl`` GUIs to ``1``. This will reduce the risk of damaging the cameras.
excellent to include, but this should be done BEFORE you acquire from guider.  That's when the star could end up on the detectors

2024-08-04 19:35 UTC, jaredmales commented on operating/on_sky.rst
> +5. You should see a star appear on ``camacq``. If the star appears out of focus, go to ``cursesINDI`` and search for ``camwfs.zNudge`` (Note:can't remember the exact command). Edit the value to apply
why not look it up in cursesINDI?

2024-08-04 19:35 UTC, jaredmales commented on operating/on_sky.rst
> +   * In the ``OffloadingCtrl`` GUI under ``Focus``, press ``Dump``.
this won't have any effect until you have raised focus gains

2024-08-04 19:35 UTC, jaredmales commented on operating/on_sky.rst
> +2. NCPC
you can't do this closed loop!  This all goes in a separate alignment section, that really should be done in lab mode on the source

2024-08-04 19:35 UTC, jaredmales commented on operating/on_sky.rst
> +#. Now use the ``Pupil Plane`` buttons in the ``coronAlignGUI`` to align the bump mask on the pupil. Set the step size to ``100`` and press the down arrow 3 times. This is typically enough to align t
this is correct, but assumes that the alignment was already done on the soruce to get the mask close.  just re-making the point that we need a separate alignment procedure (like the one that is pinned on slack)

2024-08-04 19:35 UTC, jaredmales commented on operating/on_sky.rst
> +#. In the ``Pupil Alignment`` GUI, use the keypad in the lower-righthand corner to drive the x and y avg values to 0. After each translation, wait a few seconds for the readings to stabilize. Also no
the idea is correct.  It's really something like "when x is within 0.2, steps sizes of 0.05 should be used.  The y-axis steps size can remain 0.1"

2024-08-04 19:35 UTC, jaredmales commented on operating/on_sky.rst
> +#. Once the x, y avgs are at roughly 0, set the pupil alignment loop gain to 0.1 and turn on the pupil alignment loop.
change "roughly 0" to "0 +/- 0.1"

2024-08-04 19:35 UTC, jaredmales commented on operating/pup_align_gui.png
please get a higher quality image

2025-03-31 14:55 UTC, joseph-long commented
What's going on here? It looks like a lot more changes and some regressions (introducing old typos etc)?

2026-05-05 01:51 UTC, joshua-liberman commented
- Closing this PR due to it being obsolete

2026-05-05 01:51 UTC, closed without merging